### ISSUE TITLE
Estão faltando instruções de como fazer o build e o deploy do código fonte

### ISSUE THREAD

**Issue by cleydyr** [Biblivre/Biblivre-5#1]
Para usuários não-técnicos que não usam Maven (usam ant, gradle, etc.) estão faltando instruções detalhadas de como fazer o deploy. Tentei fazer o deploy com `mvn deploy` sem qualquer configuração e o erro não é muito esclarecedor:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project biblivre-5: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Obrigado.

**Comment by Sydtrack** [comment]
O `mvn deploy` é para implantar o sistema em um tomcat em ambiente de teste, staging ou raramente em produção.

Para isso você precisará primeiro alterar o pom.xml, linhas 275-276 para apontar para o seu servidor tomcat. Depois será necessário criar o arquivo .settings na sua pasta .m2 com seu usuário e senha de deploy (como explicado em [tomcat7-maven-plugin/usage](http://tomcat.apache.org/maven-plugin-trunk/tomcat7-maven-plugin/usage.html).

https://github.com/Biblivre/Biblivre-5/blob/93f44b81f97a83bc67a5b695a16cac3f86ef1b99/pom.xml#L274-L276

Você não precisa disso se quiser apenas gerar o .war, para isso basta usar o comando `mvn package` e copiar manualmente o .war para o ambiente desejado.

**Comment by cleydyr** [comment]
Obrigado pela informação, Alberto. Estou com problemas no deployment do war no servidor de aplicação. Vou abrir uma outra issue para este caso.

Atenciosamente.
