### ISSUE TITLE
Faltando jar 

### ISSUE THREAD

**Issue by tkazu** [Biblivre/Biblivre-5#2]
import org.jzkit.search.provider.iface.IRQuery;
import org.jzkit.search.provider.iface.Searchable;
import org.jzkit.search.util.RecordModel.ArchetypeRecordFormatSpecification;
import org.jzkit.search.util.RecordModel.iso2709;
import org.jzkit.search.util.ResultSet.IRResultSet;
import org.jzkit.search.util.ResultSet.IRResultSetStatus;
import org.jzkit.search.util.ResultSet.ReadAheadEnumeration;

**Comment by cleydyr** [comment]
Oi, @tkazu. Tudo bem?

Pode explicar um pouco mais detalhadamente o seu problema? O que quer dizer "faltando jar"?

Pelo que eu entendi, você importou o projeto em alguma IDE e ele não conseguiu compilar ou a IDE indicou a falta do jar contendo as classes mencionadas no seu comentário. É isso?

Abraço.

**Comment by Sydtrack** [comment]
@tkazu, as dependêndias externas foram instaladas no maven como recomendado no README.md? Estes arquivos estão na pasta lib.

``` 
mvn install:install-file -Dfile=a2j-2.0.4.jar -DgroupId=org.jzkit -DartifactId=a2j -Dversion=2.0.4 -Dpackaging=jar
mvn install:install-file -Dfile=jzkit2_core-2.2.3.jar -DgroupId=org.jzkit -DartifactId=jzkit2_core -Dversion=2.2.3 -Dpackaging=jar
mvn install:install-file -Dfile=jzkit2_jdbc_plugin-2.2.3.jar -DgroupId=org.jzkit -DartifactId=jzkit2_jdbc_plugin -Dversion=2.2.3 -Dpackaging=jar
mvn install:install-file -Dfile=jzkit2_service-2.2.3.jar -DgroupId=org.jzkit -DartifactId=jzkit2_service -Dversion=2.2.3 -Dpackaging=jar
mvn install:install-file -Dfile=jzkit2_z3950_plugin-2.2.3.jar -DgroupId=org.jzkit -DartifactId=jzkit2_z3950_plugin -Dversion=2.2.3 -Dpackaging=jar
mvn install:install-file -Dfile=jzkit2_z3950_plugin-2.2.3.jar -DgroupId=org.jzkit -DartifactId=jzkit2_z3950_plugin -Dversion=2.2.3 -Dpackaging=jar
mvn install:install-file -Dfile=marc4j-2.5.1.beta.jar -DgroupId=org.marc4j -DartifactId=marc4j -Dversion=2.5.1.beta -Dpackaging=jar
mvn install:install-file -Dfile=z3950server-1.0.2.jar -DgroupId=br.org.biblivre -DartifactId=z3950server -Dversion=1.0.2 -Dpackaging=jar
mvn install:install-file -Dfile=itext-4.2.1.jar -DgroupId=com.lowagie -DartifactId=itext -Dversion=4.2.1 -Dpackaging=jar
mvn install:install-file -Dfile=normalizer-2.6.jar -DgroupId=com.ibm.icu -DartifactId=normalizer -Dversion=2.6 -Dpackaging=jar
```

**Comment by tkazu** [comment]
Eu importei o projeto e não estava conseguindo corrigir o erro de import na classe Z3950Client.

Eu já havia feito os mvn install: 
Tem dois mvn install repetidos... linhas 5 e 6 são iguais.

Adicionei a dependência do jzkit2_core no pom e o erro de import foi corrigido

obrigado pela ajuda

**Comment by nalomysouza** [comment]
Boa tarde, consegui. Tive que adicionar algumas dependencias. Porém, estou com problema nos styles. Existe duas bases "soltas" em webcontent, entre elas "biblivre_template_4.0.0.sql" isso deve ser adicionado também ?

![screenshot from 2018-02-01 16-12-53](https://user-images.githubusercontent.com/2711728/35698169-10934240-076b-11e8-9ce8-a0793a0e3ecf.png)

**Comment by cleydyr** [comment]
Oi, @tkazu. Tudo bem?

Passando aqui para pedir sua ajuda para fechar este PR (caso a dúvida inicial tenha sido solucionada) já que eu não tenho permissão neste repositório.

Obrigado!
