### ISSUE TITLE
Problema ao executar o projeto.

### ISSUE THREAD

**Issue by nalomysouza** [Biblivre/Biblivre-5#3]
Adicionei as libs conforme README. Porém, o projeto apresenta o seguinte problema
![screenshot from 2018-01-31 21-55-43](https://user-images.githubusercontent.com/2711728/35655813-97b03d80-06d2-11e8-9ecf-c151a49677d2.png)

alguma sugestão ? estou usando
Version: Oxygen.2 Release (4.7.2)
Java Open JDK 1.6
Apache Tomcat 7.0.84

**Comment by cleydyr** [comment]
Oi, @nalomysouza. Já executou os comandos no comentário https://github.com/Biblivre/Biblivre-5/issues/2#issuecomment-353611764?

**Comment by nalomysouza** [comment]
Deu certo. adicionei algumas dependencias, e tive que recompilar os sass. Obrigado!
