### ISSUE TITLE
SpringFramework

### ISSUE THREAD

**Issue by DenielPereira** [Biblivre/Biblivre-5#4]
Oi, eu tenho uma duvida. Quando abro o projeto no Eclipse é encontrado um erro no build path (Cannot find the class file for org.springframework.context.ApplicationContext). Como faço pra resolver isso?

**Comment by cleydyr** [comment]
Oi, @DenielPereira. Tudo bem?

Eu instalei as dependências do projeto pelo Maven conforme o [README](https://github.com/Biblivre/Biblivre-5/blob/master/README.md) e importei o projeto no Eclipse Oxygen.1a Release (4.7.1a) como um projeto Maven e não consegui ver esse erro especificamente.

Pode me confirmar se você instalou as dependências conforme o README do projeto?

**Comment by DenielPereira** [comment]
Sim, fiz tudo como vc falou e continua dando esse erro.
![capturar](https://user-images.githubusercontent.com/26224449/36983941-75acc8f2-2072-11e8-80a5-1279b6a3bd20.PNG)

**Comment by cleydyr** [comment]
@DenielPereira, poderia dizer além do que está indicado no README, exatamente que passos você seguiu para fazer a importação no Eclipse para eu ver se consigo reproduzir e resolver o problema?

Obrigado.

**Comment by DenielPereira** [comment]
Depois de fazer tudo que está indicando no README, simplesmente abri o Eclipse Oxygen.2 Release (4.7.2), File > Import... > Maven > Existing Maven Projects > Next > Browse > Finish

**Comment by cleydyr** [comment]
Eu segui os passos para reproduzir que você forneceu, apenas utilizando uma versão diferente do Eclipse e não consegui obter o mesmo resultado. Eu vou procurar e baixar a release Oxygen.2 do Eclipse e tentar novamente.

Abraço

**Comment by cleydyr** [comment]
Mesmo usando o Eclipse Oxygen.2 (4.7.2), eu não consegui obter o mesmo resultado.

Como eu sabia que essa classe está na biblioteca do Tomcat, eu associei um servidor Tomcat 6 ao workspace e consegui obter o resultado que você mostrou na imagem.

O pior é que se você consertar ele, colocando a dependência no `pom.xml`, outros erros de dependência faltando vão ocorrer. Eu vou ver se consigo fechar um `pom.xml` sem pendência e enviar um PR pra o mantenedor.

Abraço!

**Comment by cleydyr** [comment]
Saca: https://github.com/Biblivre/Biblivre-5/pull/5

**Comment by DenielPereira** [comment]
Eu adicionei as linhas que do seu PR no meu projeto, porem o erro continua :/

**Comment by cleydyr** [comment]
Oi, @DenielPereira. É o mesmo erro ou um erro parecido com uma classe diferente?

**Comment by DenielPereira** [comment]
O mesmo erro. Eu vou tentar com o Eclipse Oxygen.1a Release (4.7.1a) que vc tinha falado antes pra ver se funciona normal.

**Comment by cleydyr** [comment]
Estranho. Eu utilizei aqui um workspace fresquinho e adicionei as linhas e deu um erro com uma classe diferente. Esse erro com uma classe diferente deve sumir quando

1. associar um Tomcat ao workspace;
2. colocar os jar da pasta lib no build path.

Eu também tô utilizando o Eclipse Oxygen.2 (4.7.2).

**Comment by DenielPereira** [comment]
Consegui tirar o erro iniciando o projeto do zero e colocando as dependências do seu PR. Muito obrigado!

**Comment by cleydyr** [comment]
De nada, @DenielPereira! Fico feliz em ajudar!
